spring.application.name=sprinbootcode




# DB Connection
spring.datasource.url=jdbc:mysql://localhost:3308/HireTrack?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root

# Hibernate Settings
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl_auto=update

